// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using info_app.Data;

#nullable disable

namespace EnemQuest.Migrations
{
    [DbContext(typeof(QuestaoDbContext))]
    [Migration("20231218123818_segundo migration")]
    partial class segundomigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("info_app.Data.Questao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<int>("Competencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dificuldade")
                        .HasColumnType("TEXT");

                    b.Property<int>("Habilidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opcao1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opcao2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opcao3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opcao4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opcao5")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestaoTitulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resposta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questao");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Area = "Ciências Humanas",
                            Competencia = 2,
                            Dificuldade = "Fácil",
                            Habilidade = 6,
                            Opcao1 = "a) Alemanha",
                            Opcao2 = "b) Holanda",
                            Opcao3 = "c) Itália",
                            Opcao4 = "d) Inglaterra",
                            Opcao5 = "e) Espanha",
                            QuestaoTitulo = "O acúmulo de capitais, a modernização da agricultura, a disponibilidade de mão de obra e de recursos naturais e a força do puritanismo ajudam a explicar o pioneirismo da __________ na Revolução Industrial.Das opções abaixo listadas, o país que melhor preenche o espaço acima é:",
                            Resposta = "d) Inglaterra"
                        },
                        new
                        {
                            Id = 1002,
                            Area = "Ciências Humanas",
                            Competencia = 5,
                            Dificuldade = "Médio",
                            Habilidade = 10,
                            Opcao1 = "a) implantação da indústria doméstica rural em substituição às oficinas.",
                            Opcao2 = "b) realização da produção em grandes unidades fabris e intensa divisão do trabalho.",
                            Opcao3 = "c) mecanização da produção agrícola e consequente fixação do homem à terra.",
                            Opcao4 = "d) facilidade na compra de máquinas pelos artesãos que conseguiam financiamento para isso.",
                            Opcao5 = "e) preocupação em aumentar a produção, respeitando-se o limite da força física do trabalhador.",
                            QuestaoTitulo = "O novo processo de produção introduzido com a Revolução Industrial, no século XVIII, caracterizou-se pela:",
                            Resposta = "b) realização da produção em grandes unidades fabris e intensa divisão do trabalho."
                        },
                        new
                        {
                            Id = 1003,
                            Area = "Ciências Humanas",
                            Competencia = 7,
                            Dificuldade = "Difícil",
                            Habilidade = 14,
                            Opcao1 = "a) O rádio, o telefone e a televisão",
                            Opcao2 = "b) A locomotiva, o automóvel e a vacina",
                            Opcao3 = "c) A fotografia, o cinema e a eletricidade",
                            Opcao4 = "d) O para-raios, a calculadora e o telégrafo.",
                            Opcao5 = "e) A televisão, o computador e o iphone",
                            QuestaoTitulo = "O século XIX foi um momento repleto de invenções em vários campos do saber. Dentre elas, podemos destacar:",
                            Resposta = "c) A fotografia, o cinema e a eletricidade"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
